name: azkarapp
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
    # Packages
  percent_indicator: ^3.0.1
  flutter_screenutil: ^5.5.3+2
  auto_size_text: ^3.0.0
  provider: ^6.0.3
  shared_preferences: ^2.0.7
  cupertino_icons: ^1.0.3
    # End Packages

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0



flutter:
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Bold.ttf
        - asset: assets/fonts/Cairo-Regular.ttf

  uses-material-design: true




