name: azkarapp 

description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
    # Packages
  fluttertoast:
  percent_indicator: ^4.2.2
  flutter_screenutil: ^5.5.3+2
  auto_size_text: ^3.0.0
  provider: ^6.0.3
  shared_preferences: ^2.0.7
  cupertino_icons: ^1.0.3
  sqflite: ^2.0.3+1
    # End Packages

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0



flutter:
  assets:
    - assets/icons/
  fonts:

    - family: digital
      fonts:
        - asset: assets/fonts/digital.ttf

    - family: MM
      fonts:
        - asset: assets/fonts/ScheherazadeNew-Bold.ttf
        - asset: assets/fonts/ScheherazadeNew-Regular.ttf
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf

  uses-material-design: true




