name: azkarapp
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
 # sdk: ">=2.7.0 <3.0.0"
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
    # Packages
  percent_indicator: ^3.0.1
  get_storage: ^2.0.3
  get: ^4.3.8
  provider: ^6.0.1
  shared_preferences: ^2.0.7
  hive: ^2.0.4
  page_transition: ^2.0.4
  google_fonts: ^2.1.0


    # End Packages
  cupertino_icons: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  fonts:
    - family: Cairo
      fonts:
        - asset: fonts/Cairo-Bold.ttf
        - asset: fonts/Cairo-Regular.ttf
    - family: Tajawal
      fonts:
        - asset: fonts/Tajawal-Black.ttf
        - asset: fonts/Tajawal-Bold.ttf
        - asset: fonts/Tajawal-ExtraBold.ttf
        - asset: fonts/Tajawal-ExtraLight.ttf
        - asset: fonts/Tajawal-Light.ttf
        - asset: fonts/Tajawal-Medium.ttf
        - asset: fonts/Tajawal-Regular.ttf
    - family: Lemonada
      fonts:
        - asset: fonts/Lemonada-VariableFont_wght.ttf
    - family: Roboto Mono
      fonts:
        - asset: fonts/RobotoMono-VariableFont_wght.ttf
    - family: Janna
      fonts:
        - asset: fonts/JannaLT-Regular.ttf



  uses-material-design: true




